services:
  hammer:
    container_name: Hammer
    pull_policy: build
    build:
      context: .
      dockerfile: Hammer/Dockerfile
    volumes:
      - ${DATA_DIR}:/app/data
      - ${LOGS_DIR}:/app/logs
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - API_TOKEN=${API_TOKEN}

  hammer-db:
    container_name: hammer-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DIR}:/var/lib/postgresql
    restart: unless-stopped
