//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbedMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbedMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Hammer.Resources.EmbedMessages", typeof(EmbedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BanDescription {
            get {
                return ResourceManager.GetString("BanDescription", resourceCulture);
            }
        }
        
        internal static string DmModMail {
            get {
                return ResourceManager.GetString("DmModMail", resourceCulture);
            }
        }
        
        internal static string KickDescription {
            get {
                return ResourceManager.GetString("KickDescription", resourceCulture);
            }
        }
        
        internal static string MessageDeletionDescription {
            get {
                return ResourceManager.GetString("MessageDeletionDescription", resourceCulture);
            }
        }
        
        internal static string MessageFromStaff {
            get {
                return ResourceManager.GetString("MessageFromStaff", resourceCulture);
            }
        }
        
        internal static string MessageReportFeedback {
            get {
                return ResourceManager.GetString("MessageReportFeedback", resourceCulture);
            }
        }
        
        internal static string MuteDescription {
            get {
                return ResourceManager.GetString("MuteDescription", resourceCulture);
            }
        }
        
        internal static string TemporaryBanDescription {
            get {
                return ResourceManager.GetString("TemporaryBanDescription", resourceCulture);
            }
        }
        
        internal static string TemporaryMuteDescription {
            get {
                return ResourceManager.GetString("TemporaryMuteDescription", resourceCulture);
            }
        }
        
        internal static string WarningDescription {
            get {
                return ResourceManager.GetString("WarningDescription", resourceCulture);
            }
        }
    }
}
