//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Hammer.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CannotDeleteNonGuildMessage {
            get {
                return ResourceManager.GetString("CannotDeleteNonGuildMessage", resourceCulture);
            }
        }
        
        internal static string MessageCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessageCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string MessageStaffMemberGuildMismatch {
            get {
                return ResourceManager.GetString("MessageStaffMemberGuildMismatch", resourceCulture);
            }
        }
        
        internal static string MinIdGreaterThanMaxId {
            get {
                return ResourceManager.GetString("MinIdGreaterThanMaxId", resourceCulture);
            }
        }
        
        internal static string MinDateGreaterThanMaxDate {
            get {
                return ResourceManager.GetString("MinDateGreaterThanMaxDate", resourceCulture);
            }
        }
        
        internal static string ModeratorCannotPermanentlyMute {
            get {
                return ResourceManager.GetString("ModeratorCannotPermanentlyMute", resourceCulture);
            }
        }
        
        internal static string NoConfigurationForGuild {
            get {
                return ResourceManager.GetString("NoConfigurationForGuild", resourceCulture);
            }
        }
        
        internal static string NoEmbedForGag {
            get {
                return ResourceManager.GetString("NoEmbedForGag", resourceCulture);
            }
        }
        
        internal static string NoSuchNote {
            get {
                return ResourceManager.GetString("NoSuchNote", resourceCulture);
            }
        }
        
        internal static string NotAStaffMember {
            get {
                return ResourceManager.GetString("NotAStaffMember", resourceCulture);
            }
        }
        
        internal static string ReasonCannotBeEmpty {
            get {
                return ResourceManager.GetString("ReasonCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string StaffIsHigherLevel {
            get {
                return ResourceManager.GetString("StaffIsHigherLevel", resourceCulture);
            }
        }
        
        internal static string StaffMemberRecipientGuildMismatch {
            get {
                return ResourceManager.GetString("StaffMemberRecipientGuildMismatch", resourceCulture);
            }
        }
        
        internal static string ValueCannotBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhitespace", resourceCulture);
            }
        }
    }
}
